version: '3.8'

services:
  # Servicio para la aplicación Node.js
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # Sincroniza el código local con el del contenedor
      - ..:/workspace:cached
    # Mantiene el contenedor corriendo
    command: sleep infinity
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      # Variables de entorno para la conexión a la BD
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_NAME}
      - NODE_ENV=development

  # Servicio para la base de datos PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

volumes:
  postgres-data: